version: "1"

jobs:
  main:
    executor: local
    needs:
      - build
    commands:
      - ./bin/watcher -d ./config-examples -i 10

  build:
    executor: local
    commands:
      - shards build
    needs:
      - lint
      - test

  test:
    executor: local
    commands:
      - crystal spec

  lint:
    executor: local
    commands:
      - ameba

  version:
    executor: docker
    image: mikefarah/yq:4.5.1
    commands:
      - >
        if [ -z ${VERSION+x} ]; then
          echo "Missing variable VERSION!"
          echo "Please make sure the variable is set before running this target."
          exit 1
        fi
      - echo "Updating version ${VERSION} ..."
      - yq eval -i ".version = \"${VERSION}\"" shard.yml
      - sed -i "s/VERSION = \".*\"/VERSION = \"${VERSION}\"/" src/version.cr
      - echo "Done."
