version: "1"

jobs:
  main:
    executor: local
    needs:
      - build
    commands:
      - ./bin/watcher -d ./config-examples -i 10

  build:
    executor: local
    commands:
      - shards build
    needs:
      - lint
      - test

  test:
    executor: local
    commands:
      - crystal spec

  lint:
    executor: local
    commands:
      - ameba
