version: "1"

jobs:
  main:
    executor: local
    variables: {}
      # LOG_LEVEL: DEBUG
    commands:
      - ./bin/watcher -d ./config-examples -i 10
    needs:
      - build

  build:
    executor: local
    commands:
      - shards build
    needs:
      - lint
      - format
      - test

  test:
    executor: local
    commands:
      - crystal spec

  lint:
    executor: local
    commands:
      - ameba

  format:
    executor: local
    commands:
      - crystal tool format --check
