name: CD

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    if: "!contains(github.event.release.tag_name, '-')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Update version
        run: |
          yq eval -i ".version = \"${{ github.event.release.tag_name }}\"" shard.yml
          sed -i "s/VERSION = \".*\"/VERSION = \"${{ github.event.release.tag_name }}\"/" src/version.cr

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: boord/watcher:${{ github.event.release.tag_name }},boord/watcher:latest