name: CD

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update version
        run: |
          yq eval -i ".version = \"${{ github.event.release.tag_name }}\"" shard.yml
          sed -i "s/VERSION = \".*\"/VERSION = \"${{ github.event.release.tag_name }}\"/" src/version.cr

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: boord/watcher:${{ github.event.release.tag_name }},boord/watcher:latest
          cache-from: type=registry,ref=boord/watcher:latest
          cache-to: type=inline 

  helm:
    runs-on: ubuntu-latest

    needs: [docker]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Helm package
        run: |
          helm package helm --version ${{ github.event.release.tag_name }} --app-version ${{ github.event.release.tag_name }}
