name: CD

on:
  create:
    tags: ["*"]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Extract version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
      - name: Update version
        run: |
          yq eval -i ".version = \"${{ steps.get_version.outputs.VERSION }}\"" shard.yml
          sed -i "s/VERSION = \".*\"/VERSION = \"${{ steps.get_version.outputs.VERSION }}\"/" src/version.cr

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: boord/watcher:${{ steps.get_version.outputs.VERSION }},boord/watcher:latest