name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=boord/watcher:latest
          cache-to: type=inline

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Check formatting
        run: crystal tool format --check

      - name: Install shards
        run: shards install

      - name: Build
        run: shards build --release --no-debug --static
